name: dataops-hadoop
networks:
  dataops-net:
    external: true

services:
  namenode:
    image: apache/hadoop:3
    hostname: namenode
    command: ["hdfs", "namenode"]
    user: "1000:1000"
    ports:
      - 9870:9870
    env_file:
      - ./hadoop/config
    environment:
      ENSURE_NAMENODE_DIR: "/var/lib/hadoop-hdfs/name"
      HADOOP_LOG_DIR: "/var/log/hadoop"
    volumes:
      - ./hadoop/config:/opt/hadoop/etc/hadoop:ro
      - namenode-data:/var/lib/hadoop-hdfs/name
      - namenode-logs:/var/log/hadoop
      # - ./hadoop/conf:/etc/hadoop:ro   # (선택) XML 설정을 코드로 관리할 때
    networks: [dataops-net]

  datanode:
    image: apache/hadoop:3
    command: ["hdfs", "datanode"]
    user: "1000:1000"
    env_file:
      - ./hadoop/config
    environment:
      HADOOP_LOG_DIR: "/var/log/hadoop"
    volumes:
      - ./hadoop/config:/opt/hadoop/etc/hadoop:ro
      - datanode-data:/var/lib/hadoop-hdfs/data
      - datanode-logs:/var/log/hadoop
      # - ./hadoop/conf:/etc/hadoop:ro   # (선택)
    networks: [dataops-net]

  resourcemanager:
    image: apache/hadoop:3
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    user: "1000:1000"
    ports:
      - 8088:8088
    env_file:
      - ./hadoop/config
    environment:
      HADOOP_LOG_DIR: "/var/log/hadoop"
    volumes:
      - ./hadoop/config:/opt/hadoop/etc/hadoop:ro
      - ./hadoop/test.sh:/opt/test.sh
      - resourcemanager-logs:/var/log/hadoop
      # - ./hadoop/conf:/etc/hadoop:ro   # (선택)
    networks: [dataops-net]

  nodemanager:
    image: apache/hadoop:3
    command: ["yarn", "nodemanager"]
    user: "1000:1000"
    env_file:
      - ./hadoop/config
    environment:
      HADOOP_LOG_DIR: "/var/log/hadoop"
    volumes:
      - ./hadoop/config:/opt/hadoop/etc/hadoop:ro
      - nodemanager-logs:/var/log/hadoop
      # - ./hadoop/conf:/etc/hadoop:ro   # (선택)
    networks: [dataops-net]

volumes:
  namenode-data: {}
  namenode-logs: {}
  datanode-data: {}
  datanode-logs: {}
  resourcemanager-logs: {}
  nodemanager-logs: {}
