networks:
  dataops-net:
    external: true
services:
  postgresql:
    image: postgres:18 # 사용할 PostgreSQL 버전
    container_name: postgresql
    environment:
      POSTGRES_DB: dataops
      POSTGRES_USER: dataops
      POSTGRES_PASSWORD: dataops
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - dataops-net

volumes:
  pg_data:
